import { test, expect } from '@playwright/test'

test('Idioma: cambio inmediato, persistencia y contenido dinámico en español, inglés y japonés', async ({ page }) => {
  await page.route('https://**/*', route => route.abort())
  await page.goto('/#/')
  await page.getByRole('button', { name: '⚙ Ajustes', exact: true }).click()
  await page.getByRole('combobox', { name: 'Idioma', exact: true }).selectOption('en')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page.getByRole('heading', { name: 'Page settings', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Store', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'All games', exact: true })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search games', exact: true }).fill('Elden')
  await page.getByRole('button', { name: '⚙ Settings', exact: true }).click()
  await page.getByRole('combobox', { name: 'Language', exact: true }).selectOption('ja')
  await page.getByRole('button', { name: '完了', exact: true }).click()
  await expect(page.getByRole('searchbox', { name: 'ゲームを検索', exact: true })).toHaveValue('Elden')
  await expect(page.locator('#gamesGrid .game-title').first()).toHaveText('Elden Ring')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja')
  await expect(page.getByRole('link', { name: 'ストア', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'ログイン', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'ログイン', exact: true })).toBeVisible()
  await expect(page.getByLabel('メールアドレス', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '⚙ 設定', exact: true }).click()
  await page.getByRole('combobox', { name: '言語', exact: true }).selectOption('es')
  await page.getByRole('button', { name: 'Listo', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'es')
  await expect(page.getByRole('heading', { name: 'Iniciar sesión', exact: true })).toBeVisible()
})
