import { test, expect } from '@playwright/test'
import { Buffer } from 'node:buffer'

async function imageFile(page) {
  const data = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 800; canvas.height = 500
    const context = canvas.getContext('2d')
    const gradient = context.createLinearGradient(0, 0, 800, 500)
    gradient.addColorStop(0, '#0f6f86'); gradient.addColorStop(1, '#a55bab')
    context.fillStyle = gradient; context.fillRect(0, 0, 800, 500)
    context.fillStyle = '#ffd6ad'; context.beginPath(); context.arc(400, 180, 95, 0, Math.PI * 2); context.fill()
    context.fillStyle = '#222c4a'; context.fillRect(250, 300, 300, 200)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  return { name: 'foto-perfil.png', mimeType: 'image/png', buffer: Buffer.from(data, 'base64') }
}

test('Perfil: amigos a la derecha, portada y editor de foto persistente', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('https://**/*', route => route.abort())
  await page.setViewportSize({ width: 1440, height: 1000 })
  const registration = await page.request.post('/api/auth/register', { data: { name: 'Lucía Nexus', email: `perfil-${Date.now()}@example.test`, password: 'Perfil-test-2026!' } })
  expect(registration.ok()).toBe(true)
  await page.goto('/#/cuenta')
  await expect(page.getByRole('heading', { name: 'Lucía Nexus', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Tus amigos' })).toBeVisible()
  const hero = await page.locator('.profile-hero').boundingBox()
  const friends = await page.getByRole('complementary', { name: 'Tus amigos' }).boundingBox()
  expect(friends.x).toBeGreaterThanOrEqual(hero.x + hero.width)
  expect(Math.abs(friends.y - hero.y)).toBeLessThan(2)
  const bannerButton = await page.getByRole('button', { name: 'Cambiar banner' }).boundingBox()
  expect(bannerButton.x).toBeGreaterThan(hero.x + hero.width / 2)
  const file = await imageFile(page)
  await page.getByRole('button', { name: 'Editar foto de perfil', exact: true }).click()
  const photoChooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: /Subir una foto/ }).click()
  await (await photoChooser).setFiles(file)
  const editor = page.getByRole('dialog', { name: 'Ajustar foto de perfil' })
  await expect(editor).toBeVisible()
  await expect(editor.getByRole('button', { name: 'Guardar imagen' })).toBeEnabled()
  await editor.getByRole('button', { name: 'Acercar imagen' }).click({ clickCount: 3 })
  const frame = editor.getByRole('group', { name: 'Mover encuadre con las flechas del teclado' })
  const bounds = await frame.boundingBox()
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width / 2 + 30, bounds.y + bounds.height / 2 + 20, { steps: 8 })
  await page.mouse.up()
  await page.screenshot({ path: 'artifacts/profile-photo-editor.png', fullPage: false })
  await editor.getByRole('button', { name: 'Guardar imagen' }).click()
  await expect(editor).not.toBeVisible()
  const profile = await (await page.request.get('/api/profile')).json()
  expect(profile.imageEdits.avatar.settings.zoom).toBeGreaterThan(1)
  expect(profile.imageEdits.avatar.settings.x).toBeLessThan(50)
  expect(profile.avatar).toMatch(/^data:image\/jpeg;base64,/)
  await page.reload()
  await expect(page.locator('.profile-avatar-edit img')).toHaveAttribute('src', profile.avatar)
  await page.getByRole('button', { name: 'Cambiar foto de perfil', exact: true }).click()
  await page.getByRole('button', { name: /Ajustar foto actual/ }).click()
  await expect(editor.getByRole('slider', { name: 'Zoom', exact: true })).toHaveValue(String(profile.imageEdits.avatar.settings.zoom))
  await editor.getByRole('button', { name: 'Girar a la derecha' }).click()
  await expect(editor.getByRole('button', { name: 'Guardar imagen' })).toBeEnabled()
  await editor.getByRole('button', { name: 'Cancelar', exact: true }).click()
  expect((await (await page.request.get('/api/profile')).json()).avatar).toBe(profile.avatar)
  await page.getByRole('button', { name: 'Cambiar banner' }).click()
  const bannerChooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: /Subir una foto/ }).click()
  await (await bannerChooser).setFiles(file)
  const bannerEditor = page.getByRole('dialog', { name: 'Ajustar banner' })
  await expect(bannerEditor.getByRole('button', { name: 'Guardar imagen' })).toBeEnabled()
  await bannerEditor.getByRole('button', { name: 'Guardar imagen' }).click()
  await expect(page.locator('.profile-banner-image')).toBeVisible()
  await page.screenshot({ path: 'artifacts/profile-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 375, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await page.screenshot({ path: 'artifacts/profile-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Editar foto de perfil', exact: true }).click()
  await page.getByRole('button', { name: /Ajustar foto actual/ }).click()
  await expect(editor).toBeVisible()
  expect(await editor.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Editar foto de perfil', exact: true }).click()
  await page.getByRole('button', { name: /Eliminar foto/ }).click()
  await expect(page.getByRole('heading', { name: '¿Eliminar la foto de perfil?' })).toBeVisible()
  await page.getByRole('button', { name: 'Eliminar foto', exact: true }).click()
  await expect(page.locator('.profile-avatar-edit img')).toHaveCount(0)
  expect((await (await page.request.get('/api/profile')).json()).avatar).toBe('')
  expect(errors).toEqual([])
})
