import { test, expect } from '@playwright/test'

test('Tienda, accesibilidad y sesión a 375, 768 y 1280 píxeles', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  // Las imágenes remotas no son parte de estas pruebas funcionales.
  await page.route('https://**/*', route => route.abort())
  for (const width of [375, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/#/')
    await expect(page.getByRole('heading', { name: 'Todos los juegos', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.getByRole('button', { name: 'Ajustes', exact: false }).click()
    await page.getByRole('combobox', { name: 'Apariencia', exact: true }).selectOption('light')
    await page.getByRole('combobox', { name: 'Tamaño del texto', exact: true }).selectOption('200')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
    await expect(page.locator('html')).toHaveCSS('font-size', '32px')
    await page.getByRole('button', { name: 'Listo', exact: true }).click()
    await page.getByRole('button', { name: 'Ajustes', exact: false }).click()
    await page.getByRole('button', { name: 'Restablecer ajustes' }).click()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Ajustes', exact: false })).toBeFocused()
    await page.screenshot({ path: `artifacts/store-${width}.png`, fullPage: false })
  }
  await page.goto('/#/cuenta')
  await expect(page).toHaveURL(/#\/login/)
  await page.goto('/#/registro')
  await page.getByLabel('Nombre completo').fill('Cliente Navegador')
  await page.getByLabel('Correo electrónico', { exact: true }).fill('browser@e2e.test')
  await page.getByLabel('Contraseña', { exact: true }).fill('Cliente-e2e-123!')
  await page.getByLabel('Confirmar contraseña', { exact: true }).fill('Cliente-e2e-123!')
  await page.getByRole('button', { name: 'Crear mi cuenta' }).click()
  await expect(page).toHaveURL(/#\/cuenta$/)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Cerrar sesión' })).toBeVisible()
  await page.goto('/#/admin')
  await expect(page.getByRole('heading', { name: 'Acceso restringido' })).toBeVisible()
  expect(errors).toEqual([])
})

test('Administrador: CRUD conectado y gráfico accesible', async ({ page }) => {
  await page.route('https://**/*', route => route.abort())
  await page.setViewportSize({ width: 375, height: 900 })
  await page.goto('/#/admin/login')
  await page.getByLabel('Correo electrónico', { exact: true }).fill('admin@e2e.test')
  await page.getByLabel('Contraseña', { exact: true }).fill('Admin-e2e-123!')
  await page.getByRole('button', { name: 'Entrar al panel' }).click()
  await expect(page.getByRole('heading', { name: 'Panel de administración', exact: true })).toBeVisible()
  await page.getByText('Ver gráfico de unidades vendidas', { exact: true }).first().click()
  await expect(page.getByRole('img', { name: /Unidades vendidas por juego/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Gestionar registros' }).click()
  const dialog = page.getByRole('dialog', { name: 'Gestionar registros' })
  await dialog.getByRole('combobox', { name: 'Recurso', exact: true }).selectOption('games')
  await dialog.getByLabel('Título', { exact: true }).fill('Juego desde navegador')
  await dialog.getByLabel('Precio normal (USD)', { exact: true }).fill('15')
  await dialog.getByRole('button', { name: 'Guardar registro' }).click()
  await expect(dialog.getByText('Registro guardado.', { exact: true })).toBeVisible()
  await expect(dialog.getByText('Cargando registros…', { exact: true })).not.toBeVisible()
  await dialog.getByRole('button', { name: 'Siguiente', exact: true }).click()
  const row = dialog.getByRole('row').filter({ hasText: 'Juego desde navegador' })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Editar', exact: true }).click()
  await dialog.getByLabel('Título', { exact: true }).fill('Juego actualizado')
  await dialog.getByRole('button', { name: 'Guardar registro' }).click()
  await expect(dialog.getByText('Registro guardado.', { exact: true })).toBeVisible()
  await expect(dialog.getByText('Cargando registros…', { exact: true })).not.toBeVisible()
  await dialog.getByRole('row').filter({ hasText: 'Juego actualizado' }).getByRole('button', { name: 'Eliminar', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirmar eliminación' }).click()
  await expect(dialog.getByText('Registro eliminado.', { exact: true })).toBeVisible()
  expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Gestionar registros' })).toBeFocused()
})

test('Fallo al iniciar la IA mantiene la búsqueda normal', async ({ page }) => {
  await page.addInitScript(() => { window.Worker = class { constructor() { throw new Error('Worker unavailable') } } })
  await page.route('https://**/*', route => route.abort())
  await page.goto('/#/')
  await page.getByRole('searchbox', { name: 'Buscar juegos' }).fill('Elden')
  await page.getByRole('combobox', { name: 'Ordenar por', exact: true }).selectOption('ai')
  await expect(page.getByText(/No se pudo cargar la IA|La IA no está disponible|No se pudo iniciar la IA/)).toBeVisible({ timeout: 45000 })
  await expect(page.locator('#gamesGrid').getByRole('heading', { name: 'Elden Ring', exact: true })).toBeVisible()
})
