import { test, expect } from '@playwright/test'

async function login(page, email = 'superadmin@nexus.demo') {
  await page.goto('/#/admin/login')
  await page.getByLabel('Correo electrónico', { exact: true }).fill(email)
  await page.getByLabel('Contraseña', { exact: true }).fill('NexusDemo2026!')
  await page.getByRole('button', { name: 'Iniciar sesión' }).click()
  await expect(page.getByRole('heading', { name: 'Tu tienda, de un vistazo.' })).toBeVisible()
}
test.beforeEach(async ({ page }) => { await page.route('https://**/*', route => route.abort()) })

test('Acceso, CRUD persistente y separación del catálogo público', async ({ page }) => {
  const mutations = []
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET') mutations.push(request.url()) })
  await page.goto('/#/admin/games')
  await expect(page).toHaveURL(/#\/admin\/login$/)
  await page.getByLabel('Correo electrónico').fill('superadmin@nexus.demo')
  await page.getByLabel('Contraseña', { exact: true }).fill('incorrecta')
  await page.getByRole('button', { name: 'Iniciar sesión' }).click()
  await expect(page.getByRole('alert')).toContainText('incorrectos')
  await login(page)
  await page.goto('/#/admin/games')
  await page.getByRole('button', { name: '+ Agregar juego', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nombre *', { exact: true }).fill('Aventura de prueba')
  await dialog.getByLabel('Precio (USD)').fill('19.99')
  await dialog.getByLabel('Desarrollador').selectOption('FromSoftware')
  await dialog.getByLabel('Género').fill('Aventura')
  await dialog.getByLabel('Categoría').selectOption('Aventura')
  await dialog.getByLabel('Fecha').fill('2026-09-01')
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('searchbox', { name: 'Buscar', exact: true }).fill('Aventura de prueba')
  let row = page.getByRole('row').filter({ hasText: 'Aventura de prueba' })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Editar', exact: true }).click()
  await dialog.getByLabel('Nombre *', { exact: true }).fill('Aventura editada')
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click()
  await page.reload()
  await page.getByRole('searchbox', { name: 'Buscar', exact: true }).fill('Aventura editada')
  row = page.getByRole('row').filter({ hasText: 'Aventura editada' })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Eliminar', exact: true }).click()
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Eliminar', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No se encontraron resultados' })).toBeVisible()
  await page.goto('/#/admin/activity')
  await page.getByRole('searchbox', { name: 'Buscar', exact: true }).fill('Aventura editada')
  await expect(page.locator('tbody tr')).toHaveCount(2)
  expect(mutations).toEqual([])
  await page.goto('/#/')
  await expect(page.getByRole('heading', { name: 'Todos los juegos', exact: true })).toBeVisible()
  await expect(page.locator('.ac-root')).toHaveCount(0)
})

test('Reembolsos sincronizan venta, pago, métricas y persisten', async ({ page }) => {
  await login(page)
  await page.goto('/#/admin/refunds')
  const row = page.getByRole('row').filter({ hasText: 'REF-1' })
  await row.getByRole('button', { name: 'Aprobar', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirmar', exact: true }).click()
  await expect(row).toContainText('Aprobado')
  await expect(row.getByRole('button', { name: 'Aprobar', exact: true })).toHaveCount(0)
  await page.reload()
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem('nexus.admin.demo.v1')))
  const refund = state.refunds.find(item => item.id === 'REF-1')
  expect(state.sales.find(item => item.id === refund.saleId).status).toBe('Reembolsado')
  expect(state.payments.find(item => item.saleId === refund.saleId).status).toBe('Reembolsado')
  await page.goto('/#/admin')
  await expect(page.locator('.ac-stat').filter({ hasText: 'Reembolsos pendientes' }).locator('strong')).toHaveText('4')
})

test('Cada rol oculta secciones y bloquea las rutas directas', async ({ page }) => {
  for (const [email, allowed, denied] of [['editor@nexus.demo', 'Contenido', 'Ventas'], ['moderador@nexus.demo', 'Reseñas', 'Juegos'], ['admin@nexus.demo', 'Ventas', 'Configuración']]) {
    await login(page, email)
    const navigation = page.getByRole('navigation', { name: 'Administración', exact: true })
    await expect(navigation.getByRole('link', { name: new RegExp(allowed) })).toBeVisible()
    await expect(navigation.getByRole('link', { name: new RegExp(denied) })).toHaveCount(0)
    await page.goto('/#/admin/settings')
    await expect(page.getByRole('heading', { name: 'Acceso restringido' })).toBeVisible()
    await page.getByRole('button', { name: /Cerrar sesión/ }).click()
    await expect(page).toHaveURL(/#\/admin\/login$/)
  }
})

test('Todas las secciones, búsqueda global, móvil y preferencias', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page)
  for (const section of ['games', 'users', 'sales', 'categories', 'promotions', 'reviews', 'payments', 'refunds', 'developers', 'statistics', 'content', 'notifications', 'activity', 'settings']) {
    await page.goto(`/#/admin/${section}`)
    await expect(page.locator('main h1')).toBeVisible()
  }
  await page.getByLabel('Nombre', { exact: true }).fill('NEXUS DEMO TEST')
  await page.getByRole('combobox', { name: 'Tema', exact: true }).selectOption('Medianoche')
  await page.getByRole('button', { name: 'Guardar configuración' }).click()
  await page.reload()
  await expect(page.locator('.ac-root')).toHaveAttribute('data-admin-theme', 'Medianoche')
  await expect(page.getByLabel('Nombre', { exact: true })).toHaveValue('NEXUS DEMO TEST')
  await page.getByRole('searchbox', { name: 'Buscar en administración' }).fill('Elden Ring')
  await page.locator('.ac-search-results').getByRole('link', { name: /Juegos\s*Elden Ring/ }).click()
  await expect(page.getByRole('dialog', { name: 'Detalles de juego' })).toBeVisible()
  await page.keyboard.press('Escape')
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 960 })
    await page.goto('/#/admin')
    await expect(page.locator('main h1')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    await page.screenshot({ path: `artifacts/admin-${width}.png`, fullPage: true })
    await page.goto('/#/admin/games')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
    if (width === 375) {
      await page.getByRole('button', { name: '☰ Menú' }).click()
      await page.getByRole('navigation', { name: 'Administración', exact: true }).getByRole('link', { name: /Usuarios/ }).click()
      await expect(page.locator('main h1')).toHaveText('Usuarios.')
      await expect(page.getByRole('button', { name: '☰ Menú' })).toHaveAttribute('aria-expanded', 'false')
    }
  }
  expect(errors).toEqual([])
})

test('Promociones validan fechas y bundles; filtros y moderación funcionan', async ({ page }) => {
  await login(page)
  await page.goto('/#/admin/promotions')
  await page.getByRole('button', { name: '+ Agregar promoción' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nombre *', { exact: true }).fill('Bundle demo')
  await dialog.getByLabel('Tipo').selectOption('Bundle')
  await dialog.getByLabel('Fecha de inicio').fill('2026-10-10')
  await dialog.getByLabel('Fecha final').fill('2026-10-01')
  await dialog.getByLabel('Juegos incluidos').selectOption(['GAME-1'])
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(dialog.getByRole('alert')).toContainText('fecha final')
  await dialog.getByLabel('Fecha final').fill('2026-10-30')
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(dialog.getByRole('alert')).toContainText('al menos dos juegos')
  await dialog.getByLabel('Juegos incluidos').selectOption(['GAME-1', 'GAME-2'])
  await dialog.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('combobox', { name: 'Tipo', exact: true }).selectOption('Bundle')
  await expect(page.getByRole('row').filter({ hasText: 'Bundle demo' })).toBeVisible()
  await page.goto('/#/admin/reviews')
  await page.getByRole('combobox', { name: 'Estado', exact: true }).selectOption('Reportada')
  const count = await page.locator('tbody tr').count()
  await page.locator('tbody tr').first().getByRole('button', { name: 'Aprobar', exact: true }).click()
  await expect(page.locator('tbody tr')).toHaveCount(count - 1)
})

test('Un fallo de almacenamiento no aplica cambios ni borra datos', async ({ page }) => {
  await login(page)
  await page.goto('/#/admin/refunds')
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError') } })
  const row = page.getByRole('row').filter({ hasText: 'REF-1' })
  await row.getByRole('button', { name: 'Aprobar', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirmar', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(row).toContainText('Pendiente')
  await expect(page.getByRole('alert')).toContainText('almacenamiento')
})
